export default {
    availableExtensions: {
        default: [
            'jpg',
            'jpeg',
            'bmp',
            'png',
            'gif',
            'svg',
            'js',
            'map',
            'ico',
            'css',
            'less',
            'scss',
            'pdf',
            'swf',
            'txt',
            'xml',
            'xls',
            'eot',
            'woff',
            'woff2',
            'ttf',
            'flv',
            'wmv',
            'mp3',
            'ogg',
            'wav',
            'avi',
            'mov',
            'mp4',
            'mpeg',
            'webm',
            'mkv',
            'rar',
            'zip'
        ],
        assets: [
            'jpg',
            'jpeg',
            'bmp',
            'png',
            'gif',
            'ico',
            'css',
            'js',
            'woff',
            'svg',
            'ttf',
            'eot',
            'json',
            'md',
            'less',
            'sass',
            'scss'
        ],
        images: [
            'jpg',
            'jpeg',
            'bmp',
            'png',
            'gif',
            'svg',
            'webp'
        ],
        videos: [
            'mp4',
            'avi',
            'mov',
            'mpg',
            'mpeg',
            'mkv',
            'webm'
        ],
        audio: [
            'mp3',
            'wav',
            'wma',
            'm4a',
            'ogg'
        ],
        misc: []
    }
};
